name:                crc24
version:             0.1.0.0
github:              "RomeoGolf/crc24"
license:             MIT
author:              "RomeoGolf"
maintainer:          "triangulumsoft@gmail.com"
copyright:           "2020 RomeoGolf"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at https://github.com/RomeoGolf/crc24#readme

dependencies:
- base >= 4.7 && < 5
- QuickCheck >= 2.13.2 && < 5
- HUnit >= 0.1 && < 3
- hspec >= 2.7.4 && < 3
- doctest >= 0.16.3 && < 3

library:
  source-dirs: src

executables:
  #crc24-exe:
  crc24:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crc24

tests:
  crc24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crc24
